-- Script de migration pour mettre a jour la table EXTERNAL_USER_REGISTRATION
-- Ajoute les colonnes manquantes heritees de BaseEntity

-- Verifier si la colonne CREATION_TIME existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'CREATION_TIME')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD CREATION_TIME DATETIME DEFAULT GETDATE();
    PRINT 'Colonne CREATION_TIME ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne CREATION_TIME existe deja';
END

-- Verifier si la colonne DATE_MODIFIED existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'DATE_MODIFIED')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD DATE_MODIFIED DATETIME DEFAULT GETDATE();
    PRINT 'Colonne DATE_MODIFIED ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne DATE_MODIFIED existe deja';
END

-- Verifier si la colonne MODIFIER existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'MODIFIER')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD MODIFIER NVARCHAR(100);
    PRINT 'Colonne MODIFIER ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne MODIFIER existe deja';
END

-- Verifier si la colonne CREATED_BY existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'CREATED_BY')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD CREATED_BY NVARCHAR(100);
    PRINT 'Colonne CREATED_BY ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne CREATED_BY existe deja';
END

-- Verifier si la colonne MODIFIED_BY existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'MODIFIED_BY')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD MODIFIED_BY NVARCHAR(100);
    PRINT 'Colonne MODIFIED_BY ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne MODIFIED_BY existe deja';
END

-- Verifier si la colonne IS_DELETED existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'IS_DELETED')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD IS_DELETED BIT DEFAULT 0;
    PRINT 'Colonne IS_DELETED ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne IS_DELETED existe deja';
END

-- Verifier si la colonne VERSION existe, sinon l'ajouter
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNAL_USER_REGISTRATION' AND COLUMN_NAME = 'VERSION')
BEGIN
    ALTER TABLE EXTERNAL_USER_REGISTRATION ADD VERSION INT DEFAULT 1;
    PRINT 'Colonne VERSION ajoutee';
END
ELSE
BEGIN
    PRINT 'Colonne VERSION existe deja';
END

PRINT 'Migration terminee avec succes'; 